[package]
name = "streamingly"
version = "0.2.0"
authors = ["bazy"]
edition = "2018"

[dependencies]
actix-web = "^3"
actix-cors = "^0.5.4"
actix-files = "^0.5.0"
serde = { version = "^1.0.27", features = ["derive"] }
mysql = "^20.1.0"